version: '2'
services:
  api:
    image: my-api:latest
    container_name: my-api 
    command: make start
    ports:
      - 8086:8086
    restart: always
    volumes:
      - ./data/config/app.json:/go/src/github.com/sundogrd/content-api/data/config/app.json
      - ./data/logs:/go/src/github.com/sundogrd/content-api/data/logs
    depends_on:
      - db
      - redis
    environment:
      - GO111MODULE=on
  db:
    image: postgres:9.6-alpine
    container_name: my-api-db
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: SgQ6Vhc3u015xOL09se9
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:4-alpine
    container_name: my-api-redis
    restart: always
    volumes:
      - ./data/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf
