// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment/info.proto

package comment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comment_ECommentState int32

const (
	Comment_UNKNOWN  Comment_ECommentState = 0
	Comment_SHOW     Comment_ECommentState = 1
	Comment_WITHDRAW Comment_ECommentState = 2
)

var Comment_ECommentState_name = map[int32]string{
	0: "UNKNOWN",
	1: "SHOW",
	2: "WITHDRAW",
}

var Comment_ECommentState_value = map[string]int32{
	"UNKNOWN":  0,
	"SHOW":     1,
	"WITHDRAW": 2,
}

func (x Comment_ECommentState) String() string {
	return proto.EnumName(Comment_ECommentState_name, int32(x))
}

func (Comment_ECommentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{12, 0}
}

type ListCommentsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TargetId             int64    `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CreatorId            int64    `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             int64    `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	State                int32    `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	StartTime            uint32   `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint32   `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ReCommentId          int64    `protobuf:"varint,10,opt,name=re_comment_id,json=reCommentId,proto3" json:"re_comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{0}
}

func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(m, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

func (m *ListCommentsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ListCommentsRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *ListCommentsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCommentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsRequest) GetCreatorId() int64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *ListCommentsRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *ListCommentsRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ListCommentsRequest) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ListCommentsRequest) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ListCommentsRequest) GetReCommentId() int64 {
	if m != nil {
		return m.ReCommentId
	}
	return 0
}

type ListCommentsResponse struct {
	AppId                string     `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Comments             []*Comment `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	Total                int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32      `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32      `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{1}
}

func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(m, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ListCommentsResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *ListCommentsResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListCommentsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListCommentsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetCommentByIdRequest struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentByIdRequest) Reset()         { *m = GetCommentByIdRequest{} }
func (m *GetCommentByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentByIdRequest) ProtoMessage()    {}
func (*GetCommentByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{2}
}

func (m *GetCommentByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentByIdRequest.Unmarshal(m, b)
}
func (m *GetCommentByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentByIdRequest.Merge(m, src)
}
func (m *GetCommentByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentByIdRequest.Size(m)
}
func (m *GetCommentByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentByIdRequest proto.InternalMessageInfo

func (m *GetCommentByIdRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type GetCommentByIdResponse struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentByIdResponse) Reset()         { *m = GetCommentByIdResponse{} }
func (m *GetCommentByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentByIdResponse) ProtoMessage()    {}
func (*GetCommentByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{3}
}

func (m *GetCommentByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentByIdResponse.Unmarshal(m, b)
}
func (m *GetCommentByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetCommentByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentByIdResponse.Merge(m, src)
}
func (m *GetCommentByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentByIdResponse.Size(m)
}
func (m *GetCommentByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentByIdResponse proto.InternalMessageInfo

func (m *GetCommentByIdResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type CreateCommentRequest struct {
	AppId                string                                    `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Comment              *CreateCommentRequest_CommentCreateParams `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{4}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateCommentRequest) GetComment() *CreateCommentRequest_CommentCreateParams {
	if m != nil {
		return m.Comment
	}
	return nil
}

type CreateCommentRequest_CommentCreateParams struct {
	TargetId             int64    `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	CreatorId            int64    `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReCommentId          int64    `protobuf:"varint,4,opt,name=re_comment_id,json=reCommentId,proto3" json:"re_comment_id,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Extra                string   `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest_CommentCreateParams) Reset() {
	*m = CreateCommentRequest_CommentCreateParams{}
}
func (m *CreateCommentRequest_CommentCreateParams) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest_CommentCreateParams) ProtoMessage()    {}
func (*CreateCommentRequest_CommentCreateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{4, 0}
}

func (m *CreateCommentRequest_CommentCreateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest_CommentCreateParams.Unmarshal(m, b)
}
func (m *CreateCommentRequest_CommentCreateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest_CommentCreateParams.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest_CommentCreateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest_CommentCreateParams.Merge(m, src)
}
func (m *CreateCommentRequest_CommentCreateParams) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest_CommentCreateParams.Size(m)
}
func (m *CreateCommentRequest_CommentCreateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest_CommentCreateParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest_CommentCreateParams proto.InternalMessageInfo

func (m *CreateCommentRequest_CommentCreateParams) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *CreateCommentRequest_CommentCreateParams) GetCreatorId() int64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *CreateCommentRequest_CommentCreateParams) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CreateCommentRequest_CommentCreateParams) GetReCommentId() int64 {
	if m != nil {
		return m.ReCommentId
	}
	return 0
}

func (m *CreateCommentRequest_CommentCreateParams) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentRequest_CommentCreateParams) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type CreateCommentResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Comment              *Comment `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{5}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

func (m *CreateCommentResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateCommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CommentId            int64    `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentRequest) Reset()         { *m = DeleteCommentRequest{} }
func (m *DeleteCommentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentRequest) ProtoMessage()    {}
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{6}
}

func (m *DeleteCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentRequest.Unmarshal(m, b)
}
func (m *DeleteCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentRequest.Merge(m, src)
}
func (m *DeleteCommentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentRequest.Size(m)
}
func (m *DeleteCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentRequest proto.InternalMessageInfo

func (m *DeleteCommentRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteCommentRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CommentId            int64    `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentResponse) Reset()         { *m = DeleteCommentResponse{} }
func (m *DeleteCommentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentResponse) ProtoMessage()    {}
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{7}
}

func (m *DeleteCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentResponse.Unmarshal(m, b)
}
func (m *DeleteCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentResponse.Merge(m, src)
}
func (m *DeleteCommentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentResponse.Size(m)
}
func (m *DeleteCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentResponse proto.InternalMessageInfo

func (m *DeleteCommentResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteCommentResponse) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type LikeRequest struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeRequest) Reset()         { *m = LikeRequest{} }
func (m *LikeRequest) String() string { return proto.CompactTextString(m) }
func (*LikeRequest) ProtoMessage()    {}
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{8}
}

func (m *LikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeRequest.Unmarshal(m, b)
}
func (m *LikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeRequest.Marshal(b, m, deterministic)
}
func (m *LikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeRequest.Merge(m, src)
}
func (m *LikeRequest) XXX_Size() int {
	return xxx_messageInfo_LikeRequest.Size(m)
}
func (m *LikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikeRequest proto.InternalMessageInfo

func (m *LikeRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type LikeResponse struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeResponse) Reset()         { *m = LikeResponse{} }
func (m *LikeResponse) String() string { return proto.CompactTextString(m) }
func (*LikeResponse) ProtoMessage()    {}
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{9}
}

func (m *LikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeResponse.Unmarshal(m, b)
}
func (m *LikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeResponse.Marshal(b, m, deterministic)
}
func (m *LikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeResponse.Merge(m, src)
}
func (m *LikeResponse) XXX_Size() int {
	return xxx_messageInfo_LikeResponse.Size(m)
}
func (m *LikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikeResponse proto.InternalMessageInfo

func (m *LikeResponse) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type HateRequest struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HateRequest) Reset()         { *m = HateRequest{} }
func (m *HateRequest) String() string { return proto.CompactTextString(m) }
func (*HateRequest) ProtoMessage()    {}
func (*HateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{10}
}

func (m *HateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HateRequest.Unmarshal(m, b)
}
func (m *HateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HateRequest.Marshal(b, m, deterministic)
}
func (m *HateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HateRequest.Merge(m, src)
}
func (m *HateRequest) XXX_Size() int {
	return xxx_messageInfo_HateRequest.Size(m)
}
func (m *HateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HateRequest proto.InternalMessageInfo

func (m *HateRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type HateResponse struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HateResponse) Reset()         { *m = HateResponse{} }
func (m *HateResponse) String() string { return proto.CompactTextString(m) }
func (*HateResponse) ProtoMessage()    {}
func (*HateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{11}
}

func (m *HateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HateResponse.Unmarshal(m, b)
}
func (m *HateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HateResponse.Marshal(b, m, deterministic)
}
func (m *HateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HateResponse.Merge(m, src)
}
func (m *HateResponse) XXX_Size() int {
	return xxx_messageInfo_HateResponse.Size(m)
}
func (m *HateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HateResponse proto.InternalMessageInfo

func (m *HateResponse) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type Comment struct {
	CommentId            int64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	TargetId             int64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	CreatorId            int64                 `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             int64                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReCommentId          int64                 `protobuf:"varint,5,opt,name=re_comment_id,json=reCommentId,proto3" json:"re_comment_id,omitempty"`
	Content              string                `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Extra                string                `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Like                 int32                 `protobuf:"varint,8,opt,name=like,proto3" json:"like,omitempty"`
	Hate                 int32                 `protobuf:"varint,9,opt,name=hate,proto3" json:"hate,omitempty"`
	State                Comment_ECommentState `protobuf:"varint,10,opt,name=state,proto3,enum=comment.Comment_ECommentState" json:"state,omitempty"`
	CreatedAt            uint32                `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt           uint32                `protobuf:"varint,12,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Floor                uint32                `protobuf:"varint,13,opt,name=floor,proto3" json:"floor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bacb40307de091f3, []int{12}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *Comment) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Comment) GetCreatorId() int64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Comment) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Comment) GetReCommentId() int64 {
	if m != nil {
		return m.ReCommentId
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *Comment) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Comment) GetHate() int32 {
	if m != nil {
		return m.Hate
	}
	return 0
}

func (m *Comment) GetState() Comment_ECommentState {
	if m != nil {
		return m.State
	}
	return Comment_UNKNOWN
}

func (m *Comment) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Comment) GetModifiedAt() uint32 {
	if m != nil {
		return m.ModifiedAt
	}
	return 0
}

func (m *Comment) GetFloor() uint32 {
	if m != nil {
		return m.Floor
	}
	return 0
}

func init() {
	proto.RegisterEnum("comment.Comment_ECommentState", Comment_ECommentState_name, Comment_ECommentState_value)
	proto.RegisterType((*ListCommentsRequest)(nil), "comment.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "comment.ListCommentsResponse")
	proto.RegisterType((*GetCommentByIdRequest)(nil), "comment.GetCommentByIdRequest")
	proto.RegisterType((*GetCommentByIdResponse)(nil), "comment.GetCommentByIdResponse")
	proto.RegisterType((*CreateCommentRequest)(nil), "comment.CreateCommentRequest")
	proto.RegisterType((*CreateCommentRequest_CommentCreateParams)(nil), "comment.CreateCommentRequest.CommentCreateParams")
	proto.RegisterType((*CreateCommentResponse)(nil), "comment.CreateCommentResponse")
	proto.RegisterType((*DeleteCommentRequest)(nil), "comment.DeleteCommentRequest")
	proto.RegisterType((*DeleteCommentResponse)(nil), "comment.DeleteCommentResponse")
	proto.RegisterType((*LikeRequest)(nil), "comment.LikeRequest")
	proto.RegisterType((*LikeResponse)(nil), "comment.LikeResponse")
	proto.RegisterType((*HateRequest)(nil), "comment.HateRequest")
	proto.RegisterType((*HateResponse)(nil), "comment.HateResponse")
	proto.RegisterType((*Comment)(nil), "comment.Comment")
}

func init() { proto.RegisterFile("comment/info.proto", fileDescriptor_bacb40307de091f3) }

var fileDescriptor_bacb40307de091f3 = []byte{
	// 758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0x7d, 0xb6, 0xe3, 0x24, 0xbe, 0x26, 0x28, 0x1a, 0x92, 0x27, 0xbf, 0xbc, 0x02, 0x51, 0x56,
	0x11, 0xa2, 0xa9, 0x0a, 0xa8, 0x7b, 0x0a, 0x55, 0x89, 0xa0, 0xa1, 0x35, 0x54, 0x91, 0xba, 0x89,
	0xa6, 0x78, 0xa0, 0x16, 0x89, 0xed, 0xda, 0xd3, 0xaa, 0xe5, 0xe7, 0x74, 0xd9, 0x9f, 0xd0, 0x0d,
	0x52, 0x7f, 0x59, 0x35, 0x1f, 0xfe, 0xc4, 0x71, 0xe8, 0x8a, 0x99, 0x7b, 0xe7, 0x9e, 0xeb, 0x7b,
	0xe6, 0xcc, 0x21, 0x80, 0xae, 0xfc, 0xc5, 0x82, 0x78, 0xf4, 0x99, 0xeb, 0x5d, 0xfb, 0xa3, 0x20,
	0xf4, 0xa9, 0x8f, 0x1a, 0x32, 0x36, 0xf8, 0xa9, 0xc2, 0xc6, 0x99, 0x1b, 0xd1, 0x23, 0xb1, 0x8f,
	0x6c, 0xf2, 0xf9, 0x0b, 0x89, 0x28, 0xea, 0x42, 0x1d, 0x07, 0xc1, 0xcc, 0x75, 0x2c, 0xa5, 0xaf,
	0x0c, 0x0d, 0x5b, 0xc7, 0x41, 0x30, 0x76, 0xd0, 0xff, 0x60, 0x50, 0x1c, 0xde, 0x10, 0xca, 0x32,
	0x6a, 0x5f, 0x19, 0x6a, 0x76, 0x53, 0x04, 0xc6, 0x0e, 0x42, 0x50, 0x0b, 0xf0, 0x0d, 0xb1, 0xb4,
	0xbe, 0x32, 0xd4, 0x6d, 0xbe, 0x66, 0x05, 0xec, 0xef, 0x2c, 0x72, 0xef, 0x88, 0x55, 0xe3, 0x89,
	0x26, 0x0b, 0x5c, 0xb8, 0x77, 0x04, 0x6d, 0x02, 0x5c, 0x85, 0x04, 0x53, 0x3f, 0x64, 0x70, 0x3a,
	0x87, 0x33, 0x64, 0x44, 0x34, 0x0b, 0x70, 0x48, 0x3c, 0xde, 0xac, 0x2e, 0x9a, 0x89, 0xc0, 0xd8,
	0x41, 0x1d, 0xd0, 0x23, 0x8a, 0x29, 0xb1, 0x1a, 0x1c, 0x54, 0x6c, 0x18, 0x62, 0x44, 0x71, 0x48,
	0x67, 0xd4, 0x5d, 0x10, 0xab, 0xd9, 0x57, 0x86, 0x2d, 0xdb, 0xe0, 0x91, 0x4b, 0x77, 0x41, 0xd0,
	0x7f, 0xd0, 0x24, 0x9e, 0x23, 0x92, 0x06, 0x4f, 0x36, 0x88, 0xe7, 0xf0, 0xd4, 0x00, 0x5a, 0x21,
	0x99, 0x49, 0x5a, 0x58, 0x43, 0xe0, 0x0d, 0xcd, 0x90, 0x48, 0x6a, 0xc6, 0xce, 0xe0, 0x87, 0x02,
	0x9d, 0x3c, 0x59, 0x51, 0xe0, 0x7b, 0x11, 0x59, 0xc6, 0xd6, 0x2e, 0x34, 0x25, 0x60, 0x64, 0xa9,
	0x7d, 0x6d, 0x68, 0xee, 0xb5, 0x47, 0x32, 0x30, 0x92, 0x18, 0x76, 0x72, 0x82, 0x4d, 0x44, 0x7d,
	0x8a, 0xe7, 0x9c, 0x3f, 0xcd, 0x16, 0x9b, 0x84, 0xd4, 0xda, 0x32, 0x52, 0xf5, 0x3c, 0xa9, 0x83,
	0x17, 0xd0, 0x7d, 0x4d, 0xe2, 0x4f, 0x7c, 0xf9, 0x7d, 0xec, 0xc4, 0x57, 0xca, 0xd8, 0x4e, 0xc7,
	0x53, 0x24, 0xdb, 0xc9, 0x70, 0xc7, 0xf0, 0x6f, 0xb1, 0x4e, 0x4e, 0xb7, 0x03, 0xb1, 0x5c, 0x78,
	0x55, 0xd9, 0x14, 0x89, 0x9e, 0xee, 0x55, 0xe8, 0x1c, 0xb1, 0x1b, 0x8c, 0x69, 0x5b, 0x21, 0xa8,
	0xd3, 0x14, 0x5b, 0xe5, 0xd8, 0xcf, 0x53, 0xec, 0x12, 0x98, 0xb8, 0xa1, 0xc8, 0xbd, 0xc5, 0x21,
	0x5e, 0x44, 0x49, 0xf3, 0xde, 0x6f, 0x05, 0x36, 0x4a, 0x0e, 0xe4, 0x55, 0xab, 0x14, 0x54, 0x9b,
	0x17, 0xa1, 0x5a, 0x29, 0x42, 0xad, 0x20, 0xc2, 0x07, 0xa2, 0xa9, 0x3d, 0x10, 0x0d, 0xb2, 0xd8,
	0x84, 0x1e, 0x65, 0x13, 0xea, 0x7c, 0xf2, 0x78, 0xcb, 0x2e, 0x9c, 0x7c, 0xa3, 0x21, 0xe6, 0xda,
	0x36, 0x6c, 0xb1, 0x19, 0x7c, 0x80, 0x6e, 0x61, 0xf2, 0x6a, 0x91, 0xed, 0x14, 0x19, 0xac, 0xb8,
	0x9d, 0x33, 0xe8, 0x1c, 0x93, 0x39, 0x79, 0xec, 0xe5, 0xe4, 0x15, 0xa3, 0x16, 0x15, 0xf3, 0x06,
	0xba, 0x05, 0xb4, 0xea, 0x2f, 0x5d, 0x01, 0xb7, 0x0b, 0xe6, 0x99, 0x7b, 0x4b, 0x1e, 0x29, 0xd7,
	0xa7, 0xb0, 0x26, 0x4e, 0xcb, 0x9e, 0x2b, 0x8e, 0xef, 0x82, 0x79, 0x82, 0xe9, 0x5f, 0x80, 0x8b,
	0xd3, 0x8f, 0x03, 0xbf, 0xd7, 0xa0, 0x21, 0x39, 0x58, 0x71, 0xb4, 0xda, 0x40, 0xf3, 0x52, 0xd4,
	0x2a, 0xa5, 0x58, 0x5b, 0x25, 0x45, 0xbd, 0x52, 0x8a, 0xf5, 0x25, 0x52, 0x6c, 0x64, 0xa4, 0xc8,
	0xbc, 0x67, 0xee, 0xde, 0x0a, 0x1f, 0xd5, 0x6d, 0xbe, 0x66, 0xb1, 0x4f, 0xcc, 0x76, 0x0d, 0x11,
	0x63, 0x6b, 0x74, 0x10, 0x7b, 0x31, 0xf3, 0xcc, 0xf5, 0xbd, 0xad, 0xa2, 0x00, 0x47, 0xaf, 0xe4,
	0xe2, 0x82, 0x9d, 0xca, 0x78, 0x35, 0x9f, 0x8d, 0x38, 0x33, 0x4c, 0x2d, 0x53, 0x78, 0xb5, 0x8c,
	0x1c, 0x52, 0xb4, 0x0d, 0xe6, 0xc2, 0x77, 0xdc, 0x6b, 0x57, 0xe4, 0xd7, 0x78, 0x1e, 0xe2, 0xd0,
	0x21, 0xff, 0xe6, 0xeb, 0xb9, 0xef, 0x87, 0x56, 0x8b, 0xa7, 0xc4, 0x66, 0x70, 0x00, 0xad, 0x5c,
	0x37, 0x64, 0x42, 0xe3, 0xfd, 0xe4, 0x74, 0x72, 0x3e, 0x9d, 0xb4, 0xff, 0x41, 0x4d, 0xa8, 0x5d,
	0x9c, 0x9c, 0x4f, 0xdb, 0x0a, 0x5a, 0x83, 0xe6, 0x74, 0x7c, 0x79, 0x72, 0x6c, 0x1f, 0x4e, 0xdb,
	0xea, 0xde, 0x2f, 0x0d, 0xd6, 0xe3, 0x2a, 0x12, 0x7e, 0x75, 0xaf, 0x08, 0x3a, 0x65, 0x02, 0x4b,
	0xbd, 0x1e, 0x3d, 0x49, 0xa6, 0x2a, 0xf9, 0x7f, 0xd9, 0xdb, 0x5c, 0x92, 0x95, 0x02, 0x7a, 0x07,
	0xeb, 0x79, 0x73, 0x45, 0x29, 0x49, 0xa5, 0x6e, 0xdd, 0xdb, 0x5e, 0x9a, 0x97, 0x90, 0x13, 0x68,
	0xe5, 0x7c, 0x02, 0x6d, 0x56, 0x3a, 0x67, 0x6f, 0x6b, 0x59, 0x3a, 0xc5, 0xcb, 0xbd, 0xe6, 0x0c,
	0x5e, 0x99, 0x67, 0x64, 0xf0, 0xca, 0x4d, 0x60, 0x1f, 0x6a, 0xec, 0x81, 0xa2, 0x4e, 0x86, 0x99,
	0xe4, 0x75, 0xf7, 0xba, 0x85, 0x68, 0x5a, 0xc4, 0x1e, 0x5e, 0xa6, 0x28, 0xf3, 0x6a, 0x33, 0x45,
	0xd9, 0xd7, 0xf9, 0xb1, 0xce, 0x7f, 0xd3, 0xec, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xac,
	0x27, 0xb9, 0xe9, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentServiceClient interface {
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	GetCommentById(ctx context.Context, in *GetCommentByIdRequest, opts ...grpc.CallOption) (*GetCommentByIdResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	Hate(ctx context.Context, in *HateRequest, opts ...grpc.CallOption) (*HateResponse, error)
}

type commentServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommentServiceClient(cc *grpc.ClientConn) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) GetCommentById(ctx context.Context, in *GetCommentByIdRequest, opts ...grpc.CallOption) (*GetCommentByIdResponse, error) {
	out := new(GetCommentByIdResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/GetCommentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/Like", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) Hate(ctx context.Context, in *HateRequest, opts ...grpc.CallOption) (*HateResponse, error) {
	out := new(HateResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentService/Hate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
type CommentServiceServer interface {
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	GetCommentById(context.Context, *GetCommentByIdRequest) (*GetCommentByIdResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	Like(context.Context, *LikeRequest) (*LikeResponse, error)
	Hate(context.Context, *HateRequest) (*HateResponse, error)
}

// UnimplementedCommentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (*UnimplementedCommentServiceServer) ListComments(ctx context.Context, req *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (*UnimplementedCommentServiceServer) GetCommentById(ctx context.Context, req *GetCommentByIdRequest) (*GetCommentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentById not implemented")
}
func (*UnimplementedCommentServiceServer) CreateComment(ctx context.Context, req *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedCommentServiceServer) DeleteComment(ctx context.Context, req *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (*UnimplementedCommentServiceServer) Like(ctx context.Context, req *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (*UnimplementedCommentServiceServer) Hate(ctx context.Context, req *HateRequest) (*HateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hate not implemented")
}

func RegisterCommentServiceServer(s *grpc.Server, srv CommentServiceServer) {
	s.RegisterService(&_CommentService_serviceDesc, srv)
}

func _CommentService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_GetCommentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).GetCommentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/GetCommentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).GetCommentById(ctx, req.(*GetCommentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/Like",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).Like(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_Hate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).Hate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/Hate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).Hate(ctx, req.(*HateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComments",
			Handler:    _CommentService_ListComments_Handler,
		},
		{
			MethodName: "GetCommentById",
			Handler:    _CommentService_GetCommentById_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _CommentService_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentService_DeleteComment_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _CommentService_Like_Handler,
		},
		{
			MethodName: "Hate",
			Handler:    _CommentService_Hate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment/info.proto",
}
